//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSMerlin32.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSMerlin32.Resources.data", typeof(data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define ADdRess (3 bytes).
        /// </summary>
        internal static string ADR {
            get {
                return ResourceManager.GetString("ADR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define ADdRess Long (4 bytes).
        /// </summary>
        internal static string ADRL {
            get {
                return ResourceManager.GetString("ADRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define ASCii (&quot;&quot; positive, &apos;&apos; negative).
        /// </summary>
        internal static string ASC {
            get {
                return ResourceManager.GetString("ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place a CHecKsum in object code.
        /// </summary>
        internal static string CHK {
            get {
                return ResourceManager.GetString("CHK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Address (2 bytes).
        /// </summary>
        internal static string DA {
            get {
                return ResourceManager.GetString("DA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Byte (1 byte).
        /// </summary>
        internal static string DB {
            get {
                return ResourceManager.GetString("DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string DC {
            get {
                return ResourceManager.GetString("DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Dextral Character Inverted.
        /// </summary>
        internal static string DCI {
            get {
                return ResourceManager.GetString("DCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Double Byte (2 bytes).
        /// </summary>
        internal static string DDB {
            get {
                return ResourceManager.GetString("DDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeFine Byte (1 byte).
        /// </summary>
        internal static string DFB {
            get {
                return ResourceManager.GetString("DFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Storage (x bytes) (e.g. DS 10 (put $00 in 10 bytes), DS 10,$80 (put $80 in 10 bytes)).
        /// </summary>
        internal static string DS {
            get {
                return ResourceManager.GetString("DS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Word (2 bytes).
        /// </summary>
        internal static string DW {
            get {
                return ResourceManager.GetString("DW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define FLaShing text.
        /// </summary>
        internal static string FLS {
            get {
                return ResourceManager.GetString("FLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define HEX data (1 byte).
        /// </summary>
        internal static string HEX {
            get {
                return ResourceManager.GetString("HEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define INVerse text.
        /// </summary>
        internal static string INV {
            get {
                return ResourceManager.GetString("INV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define REVerse.
        /// </summary>
        internal static string REV {
            get {
                return ResourceManager.GetString("REV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define STRing with leading length (1 byte).
        /// </summary>
        internal static string STR {
            get {
                return ResourceManager.GetString("STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define STRing Long with leading length (2 bytes).
        /// </summary>
        internal static string STRL {
            get {
                return ResourceManager.GetString("STRL", resourceCulture);
            }
        }
    }
}
