//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSMerlin32.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class directives {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal directives() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSMerlin32.Resources.directives", typeof(directives).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string ANOP {
            get {
                return ResourceManager.GetString("ANOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a line of ASTerisks.
        /// </summary>
        internal static string AST {
            get {
                return ResourceManager.GetString("AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate and print CYCle times for the code.
        /// </summary>
        internal static string CYC {
            get {
                return ResourceManager.GetString("CYC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATe stamp assembly listing.
        /// </summary>
        internal static string DAT {
            get {
                return ResourceManager.GetString("DAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy section END.
        /// </summary>
        internal static string DEND {
            get {
                return ResourceManager.GetString("DEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO directive.
        /// </summary>
        internal static string DO {
            get {
                return ResourceManager.GetString("DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the name of the output binary after the directive.
        /// </summary>
        internal static string DSK {
            get {
                return ResourceManager.GetString("DSK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUMmy section start.
        /// </summary>
        internal static string DUM {
            get {
                return ResourceManager.GetString("DUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELSE condition.
        /// </summary>
        internal static string ELSE {
            get {
                return ResourceManager.GetString("ELSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of LUP.
        /// </summary>
        internal static string ELUP {
            get {
                return ResourceManager.GetString("ELUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^|\s)(?&lt;ELUP&gt;--\^)(\s|$).
        /// </summary>
        internal static string ELUPRegex {
            get {
                return ResourceManager.GetString("ELUPRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --^.
        /// </summary>
        internal static string ELUPValue {
            get {
                return ResourceManager.GetString("ELUPValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END of source file.
        /// </summary>
        internal static string END {
            get {
                return ResourceManager.GetString("END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define constant values (same as =).
        /// </summary>
        internal static string EQU {
            get {
                return ResourceManager.GetString("EQU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force ERRor.
        /// </summary>
        internal static string ERR {
            get {
                return ResourceManager.GetString("ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro EXPand control.
        /// </summary>
        internal static string EXP {
            get {
                return ResourceManager.GetString("EXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory ENDdirective for IF and DO .
        /// </summary>
        internal static string FIN {
            get {
                return ResourceManager.GetString("FIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF condition.
        /// </summary>
        internal static string IF {
            get {
                return ResourceManager.GetString("IF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define label from KeyBoarD.
        /// </summary>
        internal static string KBD {
            get {
                return ResourceManager.GetString("KBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relocate code (same as DSK in Merlin 32).
        /// </summary>
        internal static string LNK {
            get {
                return ResourceManager.GetString("LNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string LONGA {
            get {
                return ResourceManager.GetString("LONGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string LONGI {
            get {
                return ResourceManager.GetString("LONGI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiSTing control.
        /// </summary>
        internal static string LST {
            get {
                return ResourceManager.GetString("LST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiSTDO OFF areas of code.
        /// </summary>
        internal static string LSTDO {
            get {
                return ResourceManager.GetString("LSTDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat portions of the code (until the --^ directive).
        /// </summary>
        internal static string LUP {
            get {
                return ResourceManager.GetString("LUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the size for M (Accumulator) and X (X and Y Registers).
        /// </summary>
        internal static string MX {
            get {
                return ResourceManager.GetString("MX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be followed by the program&apos;s origin, e.g. org $800.
        /// </summary>
        internal static string ORG {
            get {
                return ResourceManager.GetString("ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New PAGe.
        /// </summary>
        internal static string PAG {
            get {
                return ResourceManager.GetString("PAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAUse.
        /// </summary>
        internal static string PAU {
            get {
                return ResourceManager.GetString("PAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the content of a source  file.
        /// </summary>
        internal static string PUT {
            get {
                return ResourceManager.GetString("PUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string PUTBIN {
            get {
                return ResourceManager.GetString("PUTBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use at the start of the program to write 16 bit relocatable code.
        /// </summary>
        internal static string REL {
            get {
                return ResourceManager.GetString("REL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the name of the output binary before the directive.
        /// </summary>
        internal static string SAV {
            get {
                return ResourceManager.GetString("SAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKiP lines.
        /// </summary>
        internal static string SKP {
            get {
                return ResourceManager.GetString("SKP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWeet16 opcodes.
        /// </summary>
        internal static string SW {
            get {
                return ResourceManager.GetString("SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRuncate control.
        /// </summary>
        internal static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiTLe heading.
        /// </summary>
        internal static string TTL {
            get {
                return ResourceManager.GetString("TTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the output file type (one byte: $00-$FF).
        /// </summary>
        internal static string TYP {
            get {
                return ResourceManager.GetString("TYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert macros.
        /// </summary>
        internal static string USE {
            get {
                return ResourceManager.GetString("USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string USING {
            get {
                return ResourceManager.GetString("USING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string USR {
            get {
                return ResourceManager.GetString("USR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string XC {
            get {
                return ResourceManager.GetString("XC", resourceCulture);
            }
        }
    }
}
