//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSMerlin32.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class opcodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal opcodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSMerlin32.Resources.opcodes", typeof(opcodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADd with Carry.
        /// </summary>
        internal static string ADC {
            get {
                return ResourceManager.GetString("ADC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADd with Carry Long.
        /// </summary>
        internal static string ADCL {
            get {
                return ResourceManager.GetString("ADCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitwise AND with accumulator.
        /// </summary>
        internal static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitwise AND with accumulator, Long.
        /// </summary>
        internal static string ANDL {
            get {
                return ResourceManager.GetString("ANDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASL shifts all bits left one position. 0 is shifted into bit 0 and the original bit 7 is shifted into the Carry.
        /// </summary>
        internal static string ASL {
            get {
                return ResourceManager.GetString("ASL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch if Carry Clear.
        /// </summary>
        internal static string BCC {
            get {
                return ResourceManager.GetString("BCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch if Carry Set.
        /// </summary>
        internal static string BCS {
            get {
                return ResourceManager.GetString("BCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch if EQual/Branch if zero.
        /// </summary>
        internal static string BEQ {
            get {
                return ResourceManager.GetString("BEQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIt Test.
        /// </summary>
        internal static string BIT {
            get {
                return ResourceManager.GetString("BIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch if MInus value.
        /// </summary>
        internal static string BMI {
            get {
                return ResourceManager.GetString("BMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch if Not Equal/Branch if not zero.
        /// </summary>
        internal static string BNE {
            get {
                return ResourceManager.GetString("BNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch if PLus value.
        /// </summary>
        internal static string BPL {
            get {
                return ResourceManager.GetString("BPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRanch Always.
        /// </summary>
        internal static string BRA {
            get {
                return ResourceManager.GetString("BRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software BReaK.
        /// </summary>
        internal static string BRK {
            get {
                return ResourceManager.GetString("BRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRanch always Long.
        /// </summary>
        internal static string BRL {
            get {
                return ResourceManager.GetString("BRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch if oVerflow Clear.
        /// </summary>
        internal static string BVC {
            get {
                return ResourceManager.GetString("BVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch if oVerflow Set.
        /// </summary>
        internal static string BVS {
            get {
                return ResourceManager.GetString("BVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLear Carry flag.
        /// </summary>
        internal static string CLC {
            get {
                return ResourceManager.GetString("CLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLear Decimal flag.
        /// </summary>
        internal static string CLD {
            get {
                return ResourceManager.GetString("CLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLear Interrupt flag.
        /// </summary>
        internal static string CLI {
            get {
                return ResourceManager.GetString("CLI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLear oVerflow flag.
        /// </summary>
        internal static string CLV {
            get {
                return ResourceManager.GetString("CLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoMPare accumulator with memory.
        /// </summary>
        internal static string CMP {
            get {
                return ResourceManager.GetString("CMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoMPare accumulator with memory, Long.
        /// </summary>
        internal static string CMPL {
            get {
                return ResourceManager.GetString("CMPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COProcessor empowerment (interrupt).
        /// </summary>
        internal static string COP {
            get {
                return ResourceManager.GetString("COP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComPare X with memory.
        /// </summary>
        internal static string CPX {
            get {
                return ResourceManager.GetString("CPX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComPare Y with memory.
        /// </summary>
        internal static string CPY {
            get {
                return ResourceManager.GetString("CPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECrement accumulator or memory.
        /// </summary>
        internal static string DEC {
            get {
                return ResourceManager.GetString("DEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEcrement X.
        /// </summary>
        internal static string DEX {
            get {
                return ResourceManager.GetString("DEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrement Y.
        /// </summary>
        internal static string DEY {
            get {
                return ResourceManager.GetString("DEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive OR accumulator with memory.
        /// </summary>
        internal static string EOR {
            get {
                return ResourceManager.GetString("EOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive OR accumulator with memory, Long.
        /// </summary>
        internal static string EORL {
            get {
                return ResourceManager.GetString("EORL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INCrement accumulator or memory.
        /// </summary>
        internal static string INC {
            get {
                return ResourceManager.GetString("INC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INcrement X.
        /// </summary>
        internal static string INX {
            get {
                return ResourceManager.GetString("INX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INcrement Y.
        /// </summary>
        internal static string INY {
            get {
                return ResourceManager.GetString("INY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JuMp, Long.
        /// </summary>
        internal static string JML {
            get {
                return ResourceManager.GetString("JML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JuMP.
        /// </summary>
        internal static string JMP {
            get {
                return ResourceManager.GetString("JMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JuMP, Long.
        /// </summary>
        internal static string JMPL {
            get {
                return ResourceManager.GetString("JMPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to Subroutine, Long.
        /// </summary>
        internal static string JSL {
            get {
                return ResourceManager.GetString("JSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to SubRoutine.
        /// </summary>
        internal static string JSR {
            get {
                return ResourceManager.GetString("JSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoaD Accumulator.
        /// </summary>
        internal static string LDA {
            get {
                return ResourceManager.GetString("LDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoaD Accumulator, Long.
        /// </summary>
        internal static string LDAL {
            get {
                return ResourceManager.GetString("LDAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoaD X register.
        /// </summary>
        internal static string LDX {
            get {
                return ResourceManager.GetString("LDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoaD Y register.
        /// </summary>
        internal static string LDY {
            get {
                return ResourceManager.GetString("LDY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSR shifts all bits right one position. 0 is shifted into bit 7 and the original bit 0 is shifted into the Carry.
        /// </summary>
        internal static string LSR {
            get {
                return ResourceManager.GetString("LSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block MoVe Negative.
        /// </summary>
        internal static string MVN {
            get {
                return ResourceManager.GetString("MVN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block MoVe Positive.
        /// </summary>
        internal static string MVP {
            get {
                return ResourceManager.GetString("MVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No OPeration.
        /// </summary>
        internal static string NOP {
            get {
                return ResourceManager.GetString("NOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitwise OR Accumulator with memory.
        /// </summary>
        internal static string ORA {
            get {
                return ResourceManager.GetString("ORA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitwise OR Accumulator with memory, Long.
        /// </summary>
        internal static string ORAL {
            get {
                return ResourceManager.GetString("ORAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Effective Address.
        /// </summary>
        internal static string PEA {
            get {
                return ResourceManager.GetString("PEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Effective Indirect address.
        /// </summary>
        internal static string PEI {
            get {
                return ResourceManager.GetString("PEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push program countEr Relative.
        /// </summary>
        internal static string PER {
            get {
                return ResourceManager.GetString("PER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PusH Accumulator.
        /// </summary>
        internal static string PHA {
            get {
                return ResourceManager.GetString("PHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PusH data Bank register.
        /// </summary>
        internal static string PHB {
            get {
                return ResourceManager.GetString("PHB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PusH Direct page register.
        /// </summary>
        internal static string PHD {
            get {
                return ResourceManager.GetString("PHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PusH program banK register.
        /// </summary>
        internal static string PHK {
            get {
                return ResourceManager.GetString("PHK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PusH Processor status flags.
        /// </summary>
        internal static string PHP {
            get {
                return ResourceManager.GetString("PHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PusH X.
        /// </summary>
        internal static string PHX {
            get {
                return ResourceManager.GetString("PHX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PusH Y.
        /// </summary>
        internal static string PHY {
            get {
                return ResourceManager.GetString("PHY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Accumulator.
        /// </summary>
        internal static string PLA {
            get {
                return ResourceManager.GetString("PLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull data Bank register.
        /// </summary>
        internal static string PLB {
            get {
                return ResourceManager.GetString("PLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Direct page register.
        /// </summary>
        internal static string PLD {
            get {
                return ResourceManager.GetString("PLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Processor status flags.
        /// </summary>
        internal static string PLP {
            get {
                return ResourceManager.GetString("PLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull X.
        /// </summary>
        internal static string PLX {
            get {
                return ResourceManager.GetString("PLX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Y.
        /// </summary>
        internal static string PLY {
            get {
                return ResourceManager.GetString("PLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REset Processor status flag.
        /// </summary>
        internal static string REP {
            get {
                return ResourceManager.GetString("REP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROtate Left accumulator or memory.
        /// </summary>
        internal static string ROL {
            get {
                return ResourceManager.GetString("ROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROtate Right accumulator or memory.
        /// </summary>
        internal static string ROR {
            get {
                return ResourceManager.GetString("ROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReTurn from Interrupt.
        /// </summary>
        internal static string RTI {
            get {
                return ResourceManager.GetString("RTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReTurn from subroutine, Long.
        /// </summary>
        internal static string RTL {
            get {
                return ResourceManager.GetString("RTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReTurn from Subroutine; pulls the top two bytes off the stack (low byte first) and transfers program control to that address+1.
        /// </summary>
        internal static string RTS {
            get {
                return ResourceManager.GetString("RTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuBtract with Carry.
        /// </summary>
        internal static string SBC {
            get {
                return ResourceManager.GetString("SBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuBtract with Carry Long.
        /// </summary>
        internal static string SBCL {
            get {
                return ResourceManager.GetString("SBCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEt Carry flag.
        /// </summary>
        internal static string SEC {
            get {
                return ResourceManager.GetString("SEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEt Decimal flag.
        /// </summary>
        internal static string SED {
            get {
                return ResourceManager.GetString("SED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEt Interrupt flag.
        /// </summary>
        internal static string SEI {
            get {
                return ResourceManager.GetString("SEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEt Processor status flag.
        /// </summary>
        internal static string SEP {
            get {
                return ResourceManager.GetString("SEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STore Accumulator to memory.
        /// </summary>
        internal static string STA {
            get {
                return ResourceManager.GetString("STA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STore Accumulator to memory, Long.
        /// </summary>
        internal static string STAL {
            get {
                return ResourceManager.GetString("STAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SToP the clock.
        /// </summary>
        internal static string STP {
            get {
                return ResourceManager.GetString("STP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STore X to memory.
        /// </summary>
        internal static string STX {
            get {
                return ResourceManager.GetString("STX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STore Y to memory.
        /// </summary>
        internal static string STY {
            get {
                return ResourceManager.GetString("STY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STore Zero to memory.
        /// </summary>
        internal static string STZ {
            get {
                return ResourceManager.GetString("STZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Accumulator to X.
        /// </summary>
        internal static string TAX {
            get {
                return ResourceManager.GetString("TAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Accumulator to Y.
        /// </summary>
        internal static string TAY {
            get {
                return ResourceManager.GetString("TAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer aCcumulator to Direct page.
        /// </summary>
        internal static string TCD {
            get {
                return ResourceManager.GetString("TCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer aCcumulator to Stack page.
        /// </summary>
        internal static string TCS {
            get {
                return ResourceManager.GetString("TCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Direct page to aCcumulator.
        /// </summary>
        internal static string TDC {
            get {
                return ResourceManager.GetString("TDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test and Reset Bit.
        /// </summary>
        internal static string TRB {
            get {
                return ResourceManager.GetString("TRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test and Set Bit.
        /// </summary>
        internal static string TSB {
            get {
                return ResourceManager.GetString("TSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Stack pointer to aCcumulator.
        /// </summary>
        internal static string TSC {
            get {
                return ResourceManager.GetString("TSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Stack pointer to X.
        /// </summary>
        internal static string TSX {
            get {
                return ResourceManager.GetString("TSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer X to Accumulator.
        /// </summary>
        internal static string TXA {
            get {
                return ResourceManager.GetString("TXA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer X to Stack pointer.
        /// </summary>
        internal static string TXS {
            get {
                return ResourceManager.GetString("TXS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer X to Y.
        /// </summary>
        internal static string TXY {
            get {
                return ResourceManager.GetString("TXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Y to Accumulator.
        /// </summary>
        internal static string TYA {
            get {
                return ResourceManager.GetString("TYA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Y to X.
        /// </summary>
        internal static string TYX {
            get {
                return ResourceManager.GetString("TYX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAIt for interrupt.
        /// </summary>
        internal static string WAI {
            get {
                return ResourceManager.GetString("WAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved for future use, it performs no operation.
        /// </summary>
        internal static string WDM {
            get {
                return ResourceManager.GetString("WDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXchange low and high byte of the Accumulator.
        /// </summary>
        internal static string XBA {
            get {
                return ResourceManager.GetString("XBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXchange Carry and Emulation.
        /// </summary>
        internal static string XCE {
            get {
                return ResourceManager.GetString("XCE", resourceCulture);
            }
        }
    }
}
